env:
  browser: true
  #es2021: true #Unknown. Detected by husky
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 10
  sourceType: module
plugins:
  - react
rules: {
}
